language: android
jdk: oraclejdk8
notifications:
  email: false
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - add-on
    - extra
script:
   - ./gradlew clean build